### ISSUE TITLE
google-ocr stopped working suddenly

### ISSUE THREAD

**Issue by lokeshh** [hrishikeshrt/google_drive_ocr#7]
* google-drive-ocr version: google-ocr 0.2.6
* Python version: 3.11.5
* Operating System: MacOS 14.0 (23A344)

### Description

It was working earlier but stopped a few days ago. Following is the command I ran and the error.

### What I Did

```
> google-ocr -i image.png --client-secret client_secret_11_oct_2023.json --debug                                                                                                   

{'__module__': 'google_drive_ocr.cli', 'image': 'image.png', 'batch': None, 'image_dir': None, 'output': None, 'extension': '.png', 'suffix': '.google.txt', 'pdf': None, 'pages': None, 'client_secret': 'client_secret_11_oct_2023.json', 'upload_folder_id': None, 'workers': 1, 'no_keep': False, 'verbose': False, 'debug': True, '__dict__': <attribute '__dict__' of 'Config' objects>, '__weakref__': <attribute '__weakref__' of 'Config' objects>, '__doc__': None, 'config_file': None, 'write_out_config_file_to_this_path': None}
Making request: POST https://oauth2.googleapis.com/token
Starting new HTTPS connection (1): oauth2.googleapis.com:443
https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/usr/local/bin/google-ocr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_drive_ocr/cli.py", line 117, in main
    app = GoogleOCRApplication(
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/usr/local/lib/python3.11/site-packages/google_drive_ocr/application.py", line 98, in __post_init__
    creds = self.get_credentials()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_drive_ocr/application.py", line 144, in get_credentials
    creds.refresh(Request())
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/credentials.py", line 344, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/reauth.py", line 365, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/_client.py", line 72, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

**Comment by hrishikeshrt** [comment]
The issue seems to be with authentication with google.
When you say it was working earlier but suddenly stopped, do you mean in the same pc/environment?
Or has there been a change in the previous working environment?

Could you try removing old `client_secret.json` and redownloading and authenticating?

**Comment by lokeshh** [comment]
Yes, it stopped in the same environment. I tried with new client secret twice but still the same issue.

Also, I remember that when I put a new client secret it opens a browser window and asks for authentication but nothing like that happens this time, when I tried to authenticate with the new client secret.

**Comment by lokeshh** [comment]
@hrishikeshrt The [setup instructions](client_secret_811310224170-thfv0qksbomobnpabapkgke6vbtcl5p2.apps.googleusercontent.com.json) are outdated. 

What should I select here?

<img width="604" alt="image" src="https://github.com/hrishikeshrt/google_drive_ocr/assets/7677524/d94ae4ad-d643-46c0-af51-ce81ce4c8cef">

**Comment by hrishikeshrt** [comment]
Please select "Desktop app".

**Comment by lokeshh** [comment]
Still the same issue - 

```
$ cat desktop-client.json                                                                                                                                                          ─╯
{"installed":{"client_id":"811310224170-pa000boh80ilr12b5io***********.apps.googleusercontent.com","project_id":"loco-193117","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"GOCSPX-o6wx0sK2slNnalrU5pBc_*******","redirect_uris":["http://localhost"]}}%

$ google-ocr -i image.png --client-secret ./desktop-client.json --debug                                                                                                            
{'__module__': 'google_drive_ocr.cli', 'image': 'image.png', 'batch': None, 'image_dir': None, 'output': None, 'extension': '.png', 'suffix': '.google.txt', 'pdf': None, 'pages': None, 'client_secret': './desktop-client.json', 'upload_folder_id': None, 'workers': 1, 'no_keep': False, 'verbose': False, 'debug': True, '__dict__': <attribute '__dict__' of 'Config' objects>, '__weakref__': <attribute '__weakref__' of 'Config' objects>, '__doc__': None, 'config_file': None, 'write_out_config_file_to_this_path': None}
Making request: POST https://oauth2.googleapis.com/token
Starting new HTTPS connection (1): oauth2.googleapis.com:443
https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/usr/local/bin/google-ocr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_drive_ocr/cli.py", line 117, in main
    app = GoogleOCRApplication(
          ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 9, in __init__
  File "/usr/local/lib/python3.11/site-packages/google_drive_ocr/application.py", line 98, in __post_init__
    creds = self.get_credentials()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google_drive_ocr/application.py", line 144, in get_credentials
    creds.refresh(Request())
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/credentials.py", line 344, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/reauth.py", line 365, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/usr/local/lib/python3.11/site-packages/google/oauth2/_client.py", line 72, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

**Comment by lokeshh** [comment]
Finally, I found the fix. 

The issue is that the refresh token expires after a while and hence the requests fail. See https://stackoverflow.com/questions/66474383/python-oauth-after-few-days-fails-refreshing-tokens-with-invalid-grant-error

The workaround is to delete the token file using `rm ~/.credentials/token.json` and now it works as before.

**Comment by hrishikeshrt** [comment]
Glad that you could get it working.
Thank you for pointing out the solution.
